### ISSUE TITLE
Implicit Flow callback URL parameters

### ISSUE THREAD

**Issue by matosf** [zalando/planb-provider#105]
Hi,

Using Implicit Flow, in the consent screen, these are the URLs the user gets redirected to if he clicks Allow/Deny:

http://localhost:8080/callback**?**access_token=JWT_TOKEN&token_type=Bearer&expires_in=28800&scope=uid&state=

http://localhost:8080/callback**?**error=access_denied&state=

This URL comes from the server in the Location header.

There is an issue with this URL, because the OAuth2 Spec indicates that they should be passed as fragments (https://tools.ietf.org/html/rfc6749#section-4.2.2) and not query parameters, i.e.:

http://localhost:8080/callback**#**access_token=JWT_TOKEN&token_type=Bearer&expires_in=28800&scope=uid&state=

http://localhost:8080/callback**#**error=access_denied&state=

**Comment by hjacobs** [comment]
@matosf you are right, the Authorization Code Grant flow uses query parameters (https://tools.ietf.org/html/rfc6749#section-4.1.2), but Implicit Grant flow not.

**Comment by matosf** [comment]
submitted PR: https://github.com/zalando/planb-provider/pull/106
