### ISSUE TITLE
Remove Lombok

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#108]

**Comment by harti2006** [comment]
In favor of [Immutables](http://immutables.github.io/)?

**Comment by hjacobs** [comment]
@harti2006 I don't know --- I just know what I don't want (Lombok) :smirk:

**Comment by jbellmann** [comment]
So, what let you know that you don't want it?

**Comment by gargravarr** [comment]
Big +1 to this one. Check [here](https://github.com/zalando/planb-revocation/pull/89).

**Comment by hjacobs** [comment]
@jbellmann I think the Lombok "convenience" (e.g. not having to write getters/setters) is achievable in a different way without having to install some stupid IDE plugin. I like to use "vanilla" IDEs :smile:

**Comment by jbellmann** [comment]
@hjacobs yes you are right, I hate that too.
@gargravarr in the ticket you referenced you mentioned 'missing support for Builders', did you read the [docs](https://projectlombok.org/features/Builder.html)?

**Comment by gargravarr** [comment]
@jbellmann I did. I had issues with creating Builders with some fields with default values - and the IntelliJ plugin was not helping.

For this use case, Immutables has a much elegant approach for it IMHO. Check [here](http://immutables.github.io/immutable.html#default-attributes).

**Comment by midumitrescu** [comment]
Hello Henning,

Do you have also a reason for that?

**Comment by vroldanbet** [comment]
Is this still work in progress, @gargravarr

**Comment by vroldanbet** [comment]
won't remove lombok for the time being
