### ISSUE TITLE
Consider using consistency level EACH_QUORUM for Cassandra writes

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#22]
See https://github.com/zalando/planb-revocation/issues/29

**Comment by hjacobs** [comment]
Writes are not in the critical path (writes are only triggered by async jobs), so we can go with `EACH_QUORUM` I think.

**Comment by hjacobs** [comment]
We will use `LOCAL_QUORUM` for writes now.

**Comment by lmineiro** [comment]
After discussing this with @Jan-M we both agreed that this should be changed to `EACH_QUORUM`.

The mint bucket(s) will most probably get the new credentials although we're not guaranteeing that all DCs/regions have valid data.

**Comment by Jan-M** [comment]
:+1:

**Comment by hjacobs** [comment]
OK, will change it :-)
