### ISSUE TITLE
Add "Integration Documentation"

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#28]
Document on how to integrate with Plan B Provider, Token Info and Revocation Service:
- Supported grant types
- Access Token / JWT format
- Refresh Token (not supported!)
- API for credential rotation
- Revocation
- ...

**Comment by hjacobs** [comment]
I created a new repository with Plan B documentation: https://github.com/zalando/planb-docs

The HTML docs are automatically built and available at http://planb.readthedocs.org/

**Comment by LappleApple** [comment]
@hjacobs Does your work from March 2016 resolve the issue? If so, we can close. cc @vroldanbet
