### ISSUE TITLE
Allow non-confidential clients to authenticate without client_secret

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#44]
Non-confidential (public) OAuth clients (such as YOUR TURN) need to get JWT tokens too. This is used e.g. in Taupage: https://github.com/zalando-stups/taupage/blob/master/runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py#L179

**Comment by hjacobs** [comment]
This is allowed per RFC, see https://tools.ietf.org/html/rfc6749#section-4.3.2

> If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

**Comment by harti2006** [comment]
We should also consider #45 to not introduce a security issue here.

**Comment by vroldanbet** [comment]
@hjacobs @harti2006 I'd say this works as part of the implicit flow since looong time ago :) Shall we close it?
