### ISSUE TITLE
Authenticate service realm clients with user credentials

### ISSUE THREAD

**Issue by harti2006** [zalando/planb-provider#45]
Service users should only be allowed to authenticate, if client and user fit together.
E.g.: If we have two services configured: app-hello and app-world, and there is a client and a user for each of the apps. It should only be allowed for app-hello user to authenticate using the app-hello client. Or in other words: An access token request using the client credentials of app-hello with the user credentials of app-world will always fail.

**Comment by hjacobs** [comment]
Sounds reasonable, let's discuss this :smile:

**Comment by vetinari** [comment]
You want to break the tokens-api? ;-) Hopefully that's the only exemption...

**Comment by hjacobs** [comment]
@vetinari I see your use case :smirk:

**Comment by LappleApple** [comment]
Hey @harti2006 @hjacobs @vetinari @vroldanbet Did you guys take action here, so that we can close the Issue?

**Comment by vroldanbet** [comment]
@harti2006 isn't this a consequence of planb-provider us using resource password grant? that's what the password grant is meant to do. This would be fixed by us using client grant instead, imho :)

**Comment by harti2006** [comment]
@vroldanbet I fully agree. Client credentials grant would be the proper way to go. Let's close this issue here.
