### ISSUE TITLE
Implement OpenID Connect Provider

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#52]
As defined in http://openid.net/specs/openid-connect-core-1_0.html

**Comment by hjacobs** [comment]
I think we should issue a different JWT as `id_token`, because the ID token requires a lot more information (`aud`, some full URL in `iss`, see http://openid.net/specs/openid-connect-core-1_0.html#IDToken) --- we don't want to expand the access token just to satisfy requirements for the ID token :smirk:

**Comment by LappleApple** [comment]
@hjacobs @vroldanbet Hey, do we still want this? If not, let's close ...

**Comment by vroldanbet** [comment]
@LappleApple we don't need this feature right now
