### ISSUE TITLE
Use a syslog friendly log format

### ISSUE THREAD

**Issue by harti2006** [zalando/planb-provider#53]
I would suggest to use the [same log format](https://github.com/zalando-stups/friboo/blob/master/resources/log4j2.xml) as in friboo apps, because:

- it's optimized for syslog (omit the timestamp, as it will be prepended anyway)
- there are existing ZMON checks to watch for WARN and ERROR that could be re-used

**Comment by hjacobs** [comment]
Let's don't call it "optimized for Scalyr" --- the timestamp is actually added by Syslog, i.e. removing the timestamp makes sense when using Docker with the syslog logging driver.

**Comment by hjacobs** [comment]
OK, log now looks like (including Syslog prefix):

```
Mar 15 19:31:04 ip-172-31-137-79 docker/bd1483423819[868]: INFO  [http-nio-8080-exec-10] [POST /oauth2/access_token <- 112.34.245.67] o.z.p.p.JWTIssuer - Issued JWT for '30***88 (0f2f04d6)' requested by client /customers/testclient

**Comment by hjacobs** [comment]
The new log is much more concise (and includes IP), the old log looked like:

```
Mar 15 15:34:31 ip-172-31-156-29 docker/9bc84e60f762[886]: 2016-03-15 15:34:31.038  INFO 13 --- [nio-8080-exec-3] o.zalando.planb.provider.OIDCController  : Issued JWT for 'user123' requested by client /services/client456
