### ISSUE TITLE
Implement Implicit Grant Flow

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#55]
https://tools.ietf.org/html/rfc6749#section-4.2

**Comment by hjacobs** [comment]
The implicit grant should only be allowed for non-confidential ("public") OAuth clients.

**Comment by harti2006** [comment]
Why for public clients only? The RFC says this flow is "optimized for public clients", but not exclusive to them. Or am I missing something?

**Comment by hjacobs** [comment]
@harti2006 I think the implicit flow should be explicitly enabled as the implicit grant exposes the access token to the user (this might not be wanted). See also http://tools.ietf.org/html/rfc6749#section-10.2

> The authorization server MUST authenticate the client whenever
   possible.  If the authorization server cannot authenticate the client
   due to the client's nature, the authorization server MUST require the
   registration of any redirection URI used for receiving authorization
   responses and SHOULD utilize other means to protect resource owners
   from such potentially malicious clients.

**Comment by vroldanbet** [comment]
@hjacobs, this is already implemented, correct? Shall this be closed?

**Comment by hjacobs** [comment]
@vroldanbet yes, closing :smile:
