### ISSUE TITLE
Make realms configurable

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#58]
Realms should be completely configurable, right now we have hardcoded "/services", "/employees" and "/customers" in https://github.com/zalando/planb-provider/blob/master/src/main/java/org/zalando/planb/provider/RealmConfig.java .

**Comment by jbellmann** [comment]
@hjacobs , there is a [branch](https://github.com/zalando/planb-provider/tree/realmPlugin) already. Was created before we had a working solution, so might not be what we really need at current state.But could be a way to make this completely pluggable.

**Comment by hjacobs** [comment]
Basic configuration (realm names and implementation classes) is now possible, I will have a look into the "plugin" branch.

**Comment by vroldanbet** [comment]
@hjacobs is this still work in progress?

**Comment by hjacobs** [comment]
@vroldanbet I personally don't have more needs right now, but our "configuration" possibility is quite limited right now --- i.e. no easy way of including a completely new plugin.

**Comment by vroldanbet** [comment]
@hjacobs should we remove the work in progress tag at least then?

**Comment by hjacobs** [comment]
@vroldanbet yes, done. I'm actually closing this issue and will open a new one.
