### ISSUE TITLE
Cassandra Model changes: Add Auditing columns

### ISSUE THREAD

**Issue by Jan-M** [zalando/planb-provider#6]
I would consider moving the "realm" into the partition key, (user,realm) is the real identity.

Second please add created_by / last_modified_by fields where applicable and consider also splitting row for user up into multiple rows for "traceability".

**Comment by hjacobs** [comment]
We just discussed this with @lmineiro @sarnowski and @harti2006:

* We will not add the "realm" to the partition key (this would prevent some query use cases)
* We will add `created_by` and `last_modified_by` fields with "<REALM>/<UID>" (we don't need the `created` and `last_modified` fields as Cassandra has implicit timestamps)
* We will also use a user defined type for the passwords to store meta information

**Comment by hjacobs** [comment]
@harti2006 we should still do this...

**Comment by hjacobs** [comment]
We are now introducing a "user_password_hash" UDT (see #35).

**Comment by hjacobs** [comment]
The auditing columns still need to be properly filled with the acting user's ID..
