### ISSUE TITLE
Make templates configurable

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#60]
Make login and consent HTML templates configurable.

This should easily be possible as the Thymeleaf template path can be set via properties, see https://github.com/spring-projects/spring-boot/blob/5009933788f5f8c687719de6a697074ff80b1b69/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafProperties.java

**Comment by matosf** [comment]
Just tested it and it works.

 No need to change code. We just need to set the necessary environment variable:

```
SPRING_THYMELEAF_PREFIX=file:/templates/
```

To be able to include external resources into the template (i.e. css, javascript, images, etc), it's also necessary to set the following environment variable:

```
SPRING_RESOURCES_STATIC_LOCATIONS=file:/templates/   
```

**Comment by hjacobs** [comment]
@matosf cool, thanks.

**Comment by danieldelhoyo** [comment]
@hjacobs this one can be closed, right?

**Comment by hjacobs** [comment]
Yes, works out-of-the-box as described by @matosf  :smile:
