### ISSUE TITLE
Health indicator for cassandra connectivity

### ISSUE THREAD

**Issue by harti2006** [zalando/planb-provider#70]
Additional to the existing health indicators (disk space, hystrix) there should another one, that checks for Cassandra connectivity. Maybe we can "lend" the implementation strategy here:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/CassandraHealthIndicator.java

**Comment by hjacobs** [comment]
:+1:
