### ISSUE TITLE
Cache client / user credentials to guard against very rare C* failure

### ISSUE THREAD

**Issue by Jan-M** [zalando/planb-provider#74]
We should put some basic cache in place and thus improve on possible issues with the possibility of C\* being unavailable.

**Comment by Jan-M** [comment]
This needs some thought on how we e.g. trigger / support rotations, so it is a bit more thinking than just 60min cache I guess.

**Comment by hjacobs** [comment]
@Jan-M I would propose "never" caching user credentials, but only client credentials (more specifically only in CassandraClientRealm). User credentials might be validated against different upstream providers (upstream OAuth or Customer Service) and they must change instantly on user actions (e.g. customer changing the password).

**Comment by LappleApple** [comment]
Hey @hjacobs @Jan-M @harti2006 @jbellmann @vroldanbet  Hey all, can we close this issue? It dates back to March 2016.

Or, we could add a "Help Wanted" label.
