### ISSUE TITLE
provide an endpoint to accept consents

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-provider#77]
Provide an endpoint to accept user consents is missing, which comes handy for things like single-page applications.

**Comment by hjacobs** [comment]
?? I don't get what this issue is about, I think we have everything in place to support "single page" login "apps" which can do the POST request against /oauth2/authorize with "decision"="allow".

**Comment by vroldanbet** [comment]
@hjacobs alright, in that case this shall be closed!
