### ISSUE TITLE
upstream compatibilty - add values to scopes (instead of just boolean true)

### ISSUE THREAD

**Issue by vetinari** [zalando/planb-provider#78]
Besides the "uid" scope, there's at least the "team" scope which has a meaningful value. Suggestion is to allow for some configurable scopes to carry a string value instead of the current boolean.

**Comment by hjacobs** [comment]
@vetinari claims already can contain arbitrary values, but Token Info needs to expose these, see https://github.com/zalando/planb-tokeninfo/issues/23.

**Comment by LappleApple** [comment]
Hey @vetinari @hjacobs @vroldanbet @jbellmann @harti2006 Hey all, can we close this issue? It dates back to March 2016.

Or, we could add a "Help Wanted" label.
