### ISSUE TITLE
NPE if "scope" is not given

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-provider#8]
https://github.com/zalando/planb-provider/blob/c1e6b2877a44ac4dd34b0b352d22ca058065a72e/src/main/java/org/zalando/planb/provider/OIDCController.java#L64

**Comment by hjacobs** [comment]
NPE was mitigated, but we still need to handle the empty case and return the "default" scopes (whatever they are...)

**Comment by lmineiro** [comment]
Configurable, per realm

**Comment by sarnowski** [comment]
There are just no default scopes right now, so list will be empty. The JWT will carry the subject anyway and is sufficient enough for authentication.
