### ISSUE TITLE
Don't log full username on consent get and withdrawl

### ISSUE THREAD

**Issue by danieldelhoyo** [zalando/planb-provider#89]
see
https://github.com/zalando/planb-provider/blob/issue-86-customer-realm-scopes/src/main/java/org/zalando/planb/provider/ConsentController.java#L34

https://github.com/zalando/planb-provider/blob/issue-86-customer-realm-scopes/src/main/java/org/zalando/planb/provider/ConsentController.java#L48

**Comment by hjacobs** [comment]
See also the more important bug #90

**Comment by danieldelhoyo** [comment]
fixed
