### ISSUE TITLE
Add logo field for the client

### ISSUE THREAD

**Issue by artdaw** [zalando/planb-provider#96]
We need a string field to store base64 encoded image.

**Comment by hjacobs** [comment]
Sounds reasonable, we should discuss whether we add individual Cassandra columns for the logo image and homepage URL (which also makes sense to have).

**Comment by hjacobs** [comment]
I would propose adding two fields to the `client` table:

* `image_uri`: optional image URI which can be a Data URI with Base64 encoded image data (if this is really needed, otherwise it can point to any publicly available image)
* `homepage_url`: optional homepage URL for the application

**Comment by hjacobs** [comment]
I'm not sure whether storing base64-encoded image data in Cassandra is such a great idea..

**Comment by artdaw** [comment]
@hjacobs well, we just want to avoid security errors in case of publicly available images

**Comment by harti2006** [comment]
Actually I like hjacobs idea of "Data URIs" in your case: https://en.wikipedia.org/wiki/Data_URI_scheme

@artdaw would that be feasible for you?

**Comment by matosf** [comment]
The base64 encoded image we where talking about is the Data URI with Base64 encoded image data that hjacobs better explained, so yes @harti2006, that is OK for us.

**Comment by vroldanbet** [comment]
+1 to Data URI :)
