### ISSUE TITLE
URL encoded parameters in authorize endpoint

### ISSUE THREAD

**Issue by matosf** [zalando/planb-provider#99]
If URL encoded parameters are use in the authorize endpoint, like:
https://host/oauth2/authorize?realm=%2Ftestrealm&response_type=token&client_id=testclient&redirect_uri=http%3A%2F%2Fhost%2Fdummy-callback%2Foauth

instead of:
https://host/oauth2/authorize?realm=/testrealm&response_type=token&client_id=testclient&redirect_uri=http://host/dummy-callback/oauth

When trying to login I will always get an error:
400 Bad Request
{"error":"realm_not_found","error_description":"%2Ftestrealm not found"}

At least the realm and redirect_uri have this issue.

**Comment by hjacobs** [comment]
@matosf sorry, but this seems to be a problem in your special (Zalando-internal) JS frontend template which does not use the parameters from the server (Thymeleaf template values like in https://github.com/zalando/planb-provider/blob/master/src/main/resources/templates/login.html#L26), but instead parses the browser location URL.

I would propose either doing correct processing of the browser's URL or using the server values (setting some JS object in the Thymeleaf template).

**Comment by matosf** [comment]
@hjacobs 
Both Thymeleaf and JS Front-Ends parse the values they will POST from the URL query parameters.

The difference is that in the Thymeleaf version it URL decodes the values before setting them as form parameters. This fixes the problem because the server side will always get the decoded value.

Ideally the server side should handle the decoding, so it would work either way, but from what I could check, there is not quick clean way to enable automatic URL decoding of parameters in the server side, so we will change the JS Front-End to also do the decoding on the client side.
